version: '3.4'

services:
  company.integration-tests:
    image: company.integration-tests
    build:
      context: .
      dockerfile: Company.IntegrationTests/Dockerfile
    entrypoint: ["dotnet", "test", "--logger:trx", "--results-directory", "/var/temp"]
    volumes:
      - /opt/vsts/work/_temp:/var/temp
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CompanyTestDb;User Id=SA;Password=Easypass123;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Easypass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - testnetwork
    volumes:
      - ./CompanyDb:/scripts
    command: /bin/bash -c "/scripts/initialize.sh & /opt/mssql/bin/sqlservr"

networks:
  testnetwork:
    driver: bridge
