name: company_services
services:
  companyapi:
    image: companyapi
    container_name: companyapi
    build:
      context: .
      dockerfile: CompanyAPI/Dockerfile
    ports:
      - "5000:8081"
    depends_on:
      - sqldatabase
  sqldatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Easypass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"